version: '3.8'

services:
  dbhealth-postgres:
    image: postgres
    container_name: dbhealth-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: dbhealth
      POSTGRES_USER: admin_viewer
      POSTGRES_PASSWORD: password
    networks:
      - patient-net

  kafkac:
    image: bitnami/kafka
    container_name: kafkac
    ports:
      - "9092:9092"
      - "9094:9094"
    environment:
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafkac:9092,EXTERNAL://localhost:9094
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 0@kafkac:9093
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      KAFKA_CFG_NODE_ID: 0
      KAFKA_CFG_PROCESS_ROLES: controller,broker
    networks:
      - patient-net

  patient-service:
    image: patientimg
    container_name: patient-service
    ports:
      - "4000:4000"
    depends_on:
      - dbhealth-postgres
      - kafkac
    networks:
      - patient-net

  billing-service:
    image: billingimg
    container_name: billing-service
    ports:
      - "4001:4001"
      - "9001:9001"
    depends_on:
      - dbhealth-postgres
      - kafkac
    networks:
      - patient-net

networks:
  patient-net:
    driver: bridge
